name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SFTP to Hostinger
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: '193.203.185.189' 
          port: 65002 
          
          local_path: './'
          # FIXED: Removed the leading slash to make it relative to your home directory
          remote_path: 'domains/://parthjethava.com' 
